# run.yml
name: Run rabbit-lang CLI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python 3
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        sudo ln -sf /usr/bin/python3 /usr/bin/python
        
    - name: Install lark
      run: pip install -r requirements.txt
      
    - name: Run cli.py
      run: |
        cd rabbit-lang
        python cli.py
